linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - godox
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nosprintfhostport
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/directorius
  godox:
    keywords:
      - FIXME
  gofumpt:
    module-path: github.com/simplesurance/directorius
    extra-rules: true
