// Code generated by MockGen. DO NOT EDIT.
// Source: internal/githubclt/client.go
//
// Generated by this command:
//
//	mockgen -package mocks -source internal/githubclt/client.go -destination internal/githubclt/mocks/githubclient.go
//

// Package mocks is a generated GoMock package.
package mocks
