// Code generated by MockGen. DO NOT EDIT.
// Source: internal/jenkins/server.go
//
// Generated by this command:
//
//	mockgen -package mocks -source internal/jenkins/server.go -destination internal/autoupdate/mocks/jenkinsserver.go
//

// Package mocks is a generated GoMock package.
package mocks
